### PR TITLE
fix(delete-record): removing the ommitting of required parameters from DELETE record

### PR DESCRIPTION
**Pull request by Garethp**

### CODE REVIEW

**Comment by Garethp** [comment]
Fixes #15

**Review by mooyoul — APPROVED** [review]
Nice! Looks good to me. Huge thanks for this PR!

Before merging this, I just want to ensure this PR fixes an issue in real environment - Have you checked this changes successfully deleted Route53 Records?

**Comment by Garethp** [comment]
Yup. I ran the stack up and deleted the stack. It deleted the full stack successfully and there were no more ses records on the domain

**Pull request merged**
