### PR TITLE
change lambda function to latest version

### PR DESCRIPTION
**Pull request by cnnblike**

### CODE REVIEW

**Comment by cnnblike** [comment]
hey, @mooyoul , per contact from aws side, they are end stop for node js 18.x
please consider accept this change.

**Comment by cnnblike** [comment]
Hello,

We are contacting you as we have identified that your AWS Account currently has one or more Lambda functions using the Node.js 14 runtime.

We are ending support for Node.js 14 in AWS Lambda. This follows Node.js 14 End-Of-Life (EOL) reached on April 30, 2023 [1].

As described in the Lambda runtime support policy [2], end of support for language runtimes in Lambda happens in two stages. Starting November 27, 2023, Lambda will no longer apply security patches and other updates to the Node.js 14 runtime used by Lambda functions, and functions using Node.js 14 will no longer be eligible for technical support. In addition, you will no longer be able to create new Lambda functions using the Node.js 14 runtime. Starting January 25, 2024, you will no longer be able to update existing functions using the Node.js 14 runtime.

We recommend that you upgrade your existing Node.js 14 functions to Node.js 18 before November 27, 2023.

End of support does not impact function execution. Your functions will continue to run. However, they will be running on an unsupported runtime which is no longer maintained or patched by the AWS Lambda team.

This notification is generated for functions using the Node.js 14 runtime for the $LATEST function version. For a list of your affected Lambda functions, please see the 'Affected resources" tab of your AWS Health Dashboard

The following command shows how to use the AWS CLI [3] to list all functions in a specific region using Node.js 14, including published function versions. To find all such functions in your account, repeat this command for each region:

aws lambda list-functions --function-version ALL --region us-east-1 --output text --query "Functions[?Runtime=='nodejs14.x'].FunctionArn"

**Comment by brendanclement** [comment]
Oh nice, someone already got to this before me. Thank you for this @cnnblike .

@mooyoul could you please merge this and bump the version? It'll resolve issue https://github.com/mooyoul/aws-cdk-ses-domain-identity/issues/81

**Comment by mooyoul** [comment]
Hello everyone, I'd like to upgrade Node.js to v20 directly. will release a new version in few hours so stay tuned!

**Comment by brendanclement** [comment]
Happy new year!! @mooyoul i'm just following up on when you'll expect to have a new version out.  I'm happy to review the PR and/or help test if needed

**Comment by mooyoul** [comment]
Hello there, I've just released v2.2.0 which uses Node.js v20 runtime.

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/aws-cdk-ses-domain-identity/v/2.2.0)
- [GitHub release](https://github.com/mooyoul/aws-cdk-ses-domain-identity/releases/tag/v2.2.0)

(btw package release pipeline which uses semantic-release, had some issues - v2.1.0 was published as incomplete state. Please use v2.2.0 instead of v2.1.0)
Thanks for your patience and Happy new year!

**Pull request closed without merging**
