### PR TITLE
Migrate to CDK v2

### LINKED ISSUE #36: Upgrade to CDK v2
CDK v2 is the current stable version and requires some minor changes (making use of the new 'constructs' package in particular).

https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html

### PR DESCRIPTION
**Pull request by abonstu**
Migrate to CDK v2
https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html

Migrate tests @aws-cdk/assert (deprecated) -> aws-cdk-lib/assertions
https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/assertions/MIGRATING.md

Resolves #36

### CODE REVIEW

**Comment by St0n3Gh0st** [comment]
I am also keen to see this merged :)

**Comment by ebox86** [comment]
also interested in seeing this merged. Any ETA?

**Comment by mooyoul** [comment]
Hello all, I will release this within few hours, and I'm going to take these steps:
1. fix #8 and release it to v1 channel.
2. review & merge this pr to develop branch and add versioning policy to documentation (for cdk v1 users)
3. merge develop branch to master and release v2.

**Comment by ebox86** [comment]
hi, sorry for the ping again, did this get merged today?

**Comment by mooyoul** [comment]
Hello all, I just released v2.0.0. Please test the new version with CDK v2 and let me know the result. Specially thank @abonstu for bringing this changes! - Sending ❤️ from 🇰🇷

**Comment by mooyoul** [comment]
...and friendly ping for @ebox86 @St0n3Gh0st ;)

@ebox86 I just saw your ses-proxy project - If you're interested in implementing disposable email in Serverless with CDK. See https://github.com/mooyoul/poo.email also!

**Pull request merged**
